//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCV.DAL.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueriesContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightCV.DAL.Queries.QueriesContent", typeof(QueriesContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into DbSession (DbSessionID, SessionData, Created, LastAccessed, UserId)
        ///values (@DbSessionID, @SessionContent, @Created, @LastAccessed, @UserId);.
        /// </summary>
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select DbSessionID, SessionData, Created, LastAccessed, UserId from DbSession where DbSessionID = @sessionId;.
        /// </summary>
        internal static string GetSession {
            get {
                return ResourceManager.GetString("GetSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update DbSession
        ///set SessionData = @SessionData, LastAccessed = @LastAccessed, UserId = @UserId
        ///where DbSessionID = @DbSessionID;.
        /// </summary>
        internal static string UpdateSession {
            get {
                return ResourceManager.GetString("UpdateSession", resourceCulture);
            }
        }
    }
}
